SRC_NAME = ZeroTierOne-1.10.6
SRC_URL = https://github.com/zerotier/ZeroTierOne/archive/refs/tags/1.10.6.tar.gz

THISDIR = $(shell pwd)
FLAGS := DEFS=""
LDFLAGS := -static-libstdc++

all: 

download_test:
	
extract_test:
	 

clean:
	

romfs:
	$(ROMFSINST) $(THISDIR)/zerotier.sh /usr/bin/zerotier.sh
